name: "[Control] build pipeline"
on:
  pull_request:
    branches: [ "main" ]
    paths: [ "microservices/control", ".github/**" ]
jobs:
  test-build-control-msc:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: .
        run: yarn install

      - name: Test library
        working-directory: ./modules/library
        run: yarn test

      - name: Build modules
        working-directory: ./modules
        run: ./build.sh

     - name: Check directory
       working-directory: ./
       run: ls

     - name: Check node modules
       working-directory: ./node_modules
       run: ls | grep 'library'

      - name: Test Control Microservice
        working-directory: ./microservices/control
        run: yarn test

      - name: Build docker image
        working-directory: ./
        run: docker build -t control --build-arg BUILD_CONTEXT=control .
