name: "[Library] build pipeline"
on:
  pull_request:
    branches: [ "main" ]
    paths: [ "modules/**", ".github/**" ]
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    include: ./build-test-lib.yml
